### ISSUE TITLE
To create directory

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework4G3#12]
Do we need to create the directory ".github/workflows/filename.yml" to the main repository or to own repository?

**Comment by pratibha77118** [comment]
@tirthbha I also am confused on this. Do we really need to create another directory if one directory with name .github/workflows already exists in our homework repository.

**Comment by tirthbha** [comment]
@pratibha77118 yes we need to create the directory in own repository.

**Comment by sharmistharanit** [comment]
Thank you for letting us know.
