### ISSUE TITLE
Unit test GitHub Actions

### ISSUE THREAD

**Issue by yasmensarhan27** [ubsuny/23-Homework4G3#14]
hello, @AhmedCode99  

can you please add the code we use in the repository as a .py file not imported from Jupyter notebooks.

the GitHub actions first can't find test.py 
ERROR: file or directory not found: tests.py
[19](https://github.com/ubsuny/23-Homework4G3/actions/runs/6473785977/job/17577247718#step:5:20)

and once I changed the filename in the  unit-test GitHub action after creating a new branch
I got this error: 
ERROR: found no collectors for /home/runner/work/23-Homework4G3/23-Homework4G3/projectile_motion.ipynb
[19](https://github.com/yasmensarhan27/23-Homework4G3/actions/runs/6505043893/job/17668033302#step:5:20)

**Comment by AhmedCode99** [comment]
@yasmensarhan27 Done. The file is called projectile_module.py. It has only one function called projectile_with_drag(). This function only has one input, which is the initial velocity in m/s.
