### ISSUE TITLE
Work division

### ISSUE THREAD

**Issue by sharmistharanit** [ubsuny/23-Homework4G3#2]
Let's discuss the work division.

**Comment by AhmedCode99** [comment]
We must discuss which code we will use for this homework first. ideally the author of the code, should be the one responsible for the algorithm in this homework.

**Comment by yasmensarhan27** [comment]
hello 
I will add the codes we worked on for the last 3 homeworks

regarding the task assignments, I don't mind any of the tasks

just inform me which one will you work on and I'll take the rest

thank you

**Comment by AhmedCode99** [comment]
I will be the coder and maintainer for this repo.
