### ISSUE TITLE
Code..

### ISSUE THREAD

**Issue by uarif** [ubsuny/23-Homework4G3#20]
Hi group 3. I am not sure, are you going to check the whole code or just the unit test? Because, I think I see the whole code but not the unit test in your repository. 
Thank you

**Comment by reshnashrestha** [comment]
It seems like they are still working on  it.

**Comment by pratibha77118** [comment]
I think we run our main algorithm for pylint and unit test for pytest using github action.

**Comment by AhmedCode99** [comment]
ok

**Comment by uarif** [comment]
Yes, I got you. Thank you. I guess I could not understand the HW by that time, Now the things are clear.
