### ISSUE TITLE
Question.

### ISSUE THREAD

**Issue by uarif** [ubsuny/23-Homework4G3#22]
What is task completion in the HW (Interaction with other groups)?

**Comment by reshnashrestha** [comment]
![image](https://github.com/ubsuny/23-Homework4G3/assets/143649458/a4f97a50-c6ae-4b36-8caa-cdd04af56a46)
This is the guidelines.

**Comment by AhmedCode99** [comment]
ok

**Comment by uarif** [comment]
OK, Thanx

**Comment by uarif** [comment]
Isn't different?
There is a completion task, in the interaction with other groups. What is that?
<img width="617" alt="task complet" src="https://github.com/ubsuny/23-Homework4G3/assets/13534352/8af35c2c-215e-4a0f-9069-480293a70d8b">

**Comment by uarif** [comment]
Or. That is not interaction with other groups? That is just completing your own task, I guess? Then its fine.
