### ISSUE TITLE
Creating new labels. 

### ISSUE THREAD

**Issue by uarif** [ubsuny/23-Homework4G3#23]
Hello all, 
This is for the people who are unaware, You can also create a new label by yourself and name it whatever you want. Like, Urgent, extremely urgent, or what not. I hope it helps for someone. 
At the very end of the label button there is an edit button, and follow further. 
Thank you..

**Comment by reshnashrestha** [comment]
@uarif I don't think all can create new labels, only the maintainer has access to this. Or am I wrong?

**Comment by pratibha77118** [comment]
I also think maintainer only have access to label. I posted this issue in earlier homework too.

**Comment by AhmedCode99** [comment]
ok
