### ISSUE TITLE
output for pytest and linting

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework4G3#26]
How could we get the output for the pytest and linting using github action?

**Comment by pratibha77118** [comment]
Ya I wanna know the same. How to resolve the issues we get after running pytest and pylint?

**Comment by tirthbha** [comment]
@pratibha77118 I got it now. You need to correct each error manually until it becomes errorless.

**Comment by AhmedCode99** [comment]
git hub repo > actions> workflow> Annotations
