### ISSUE TITLE
Which code will use for this assignment?

### ISSUE THREAD

**Issue by AhmedCode99** [ubsuny/23-Homework4G3#3]
@yasmensarhan27 @sharmistharanit I will share two of my codes here. I encourage you to do the same, after we all have a good look, we can decide on a code to use.

**Comment by AhmedCode99** [comment]
This is my first code, it calculates the trajectories of projectiles with air drag:

https://colab.research.google.com/drive/1vHvNUHdNsGsBDcjR7EiAE2Id_esFVlGk?usp=sharing

**Comment by AhmedCode99** [comment]
This is my second code, it calculates the trace of matrices using 6 different methods, then plots the time it took each method:

https://colab.research.google.com/drive/1G4ME1p3G8gzT6VgSruZN7NLf9ZYKrBmU?usp=sharing

**Comment by yasmensarhan27** [comment]
https://colab.research.google.com/drive/18ogxJUWcORlk3BcK9Okh1hg_zkyBcvei#scrollTo=IQ8nnauvzyl7

**Comment by yasmensarhan27** [comment]
https://colab.research.google.com/drive/1uSQdfZu-f6mOM0YFxzJlcyeQ8bQvvPt-#scrollTo=SZI_w3xgNrQj

**Comment by AhmedCode99** [comment]
@yasmensarhan27 I cant view your code, it says access denied. Please set it so that anyone with a link can view it.

**Comment by yasmensarhan27** [comment]
done

**Comment by AhmedCode99** [comment]
I will code, I will be using my projectile motion code.
