### ISSUE TITLE
Should the Linter Action also Automatically Correct Style Issues?

### ISSUE THREAD

**Issue by WildJimmy** [ubsuny/23-Homework4G3#30]
Someone in my group raised this question, but I wanted to ask other groups. Does the linting action have to fix the issues raised by the linter, or should we be doing that manually? I know there are some linters that do both as mentioned in class, but since we're sticking with pylint I'm not sure if we should implement another action that does this

**Comment by AhmedCode99** [comment]
@WildJimmy please let me know if you figure that out

**Comment by AhmedCode99** [comment]
nope, you do not have to fix the errors.

I feel linting is useless
