### ISSUE TITLE
about license

### ISSUE THREAD

**Issue by s4il3sh** [ubsuny/23-Homework4G3#38]
did you check the availability of the license?

**Comment by sharmistharanit** [comment]
No, we have not.  Did you?

**Comment by uarif** [comment]
You can create one by yourself.

**Comment by Mosaddeq107** [comment]
> You can create one by yourself.

It is a straightforward process.

**Comment by uarif** [comment]
> > You can create one by yourself.
> 
> It is a straightforward process.

Yess,

**Comment by sharmistharanit** [comment]
Can you explain how we do that?

**Comment by LinxuanHu** [comment]
> > You can create one by yourself.
> 
> It is a straightforward process.

yeah
