### ISSUE TITLE
Code Error in algorithm part

### ISSUE THREAD

**Issue by sharmistharanit** [ubsuny/23-Homework4G3#43]
I tried to write code for unit test. However, the input parameters of the defined function are not working. what should I do? @laserlab @AhmedCode99 

<img width="640" alt="image" src="https://github.com/ubsuny/23-Homework4G3/assets/143737948/46639e49-61d4-4d47-8c1c-a358f19e270e">

**Comment by laserlab** [comment]
once you call your parameter angle the next time angles, is that correct?

**Comment by yasmensarhan27** [comment]
Hi @laserlab @sharmistharanit  
sharmista and me have found a solution to this by adding int() to the angle to convert it from float type to int type and the problem is resolved.

we also have run the pytest and it worked properly.

**Comment by laserlab** [comment]
oh for `j` I see. Yes list indexes always have to be integer. Not sure though why they weren’t in the first place. Anyway good trouble shooting @yasmensarhan27 @sharmistharanit
