### ISSUE TITLE
Choosing alternative Hw

### ISSUE THREAD

**Issue by sharmistharanit** [ubsuny/23-Homework4G3#44]
Can we use another previous hw since it is not working correctly? @laserlab @yasmensarhan27 @AhmedCode99

**Comment by AhmedCode99** [comment]
it is working fine

**Comment by AhmedCode99** [comment]
just checked again. Working fine. what is your error?

**Comment by sharmistharanit** [comment]
Check the updated code by Dr. Tim. @AhmedCode99 
For unit testing, I have to call the function from the algorithm part. There is no such function exists in the providing code. So, professor has updated the code.

**Comment by sharmistharanit** [comment]
Your code is perfectly fine. However, I have to write code for unit test.

**Comment by reshnashrestha** [comment]
@sharmistharanit Can you share the code you copied? 
I think you have to modify the code as per the task you can the code to run.

**Comment by laserlab** [comment]
in the original code everything is hardcoded. As  I mentioned in class that is not very useful and now it bites you for the unit tests.

**Comment by sharmistharanit** [comment]
The code worked for unit test. @laserlab can you check once.

**Comment by laserlab** [comment]
Can you link what I should check?

**Comment by sharmistharanit** [comment]
https://github.com/sharmistharanit/23-Homework4G3/blob/fad9c1d3f66c9b0b53f8523236ac03db558ceca4/projectile_unit_test.py

**Comment by laserlab** [comment]
The code looks ok for me but I didn’t run it. Again. Maybe an easier example would be more educational. Does it work in the GitHub action?

**Comment by yasmensarhan27** [comment]
Yeah it worked on GitHub actions and we have an output file for the purest
