### ISSUE TITLE
 How to create separate function / module for unit test?

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework4G3#56]
Any ideas will be appreciated.

**Comment by yasmensarhan27** [comment]
hi I agree with trith

the main code will be in a file.py and added to your repository 

then for the unit test you have to import this module files that contains the main code

you can import the whole file or some functions from it

**Comment by reshnashrestha** [comment]
It appeared that I did this way earlier. I was just confused with the words. 
Can you please check out my work?
[projectile_unit_test.py](https://github.com/ubsuny/23-Homework4G1/blob/main/projectile_unit_test.py)
