### ISSUE TITLE
Need explanation 

### ISSUE THREAD

**Issue by Mosaddeq107** [ubsuny/23-Homework4G3#63]
Hi all, how did you deal with this part below which is required for our homework:

# **unit test: focus on providing a seperate function / module (based on the old code - report to documentation developer what changes are needed) to the algorithm developer, so it can be implemented as a github action**

**Comment by reshnashrestha** [comment]
It appeared that I did this way earlier. I was just confused with the words. 
Can you please check out my work?
[projectile_unit_test.py](https://github.com/ubsuny/23-Homework4G1/blob/main/projectile_unit_test.py)

**Comment by Mosaddeq107** [comment]
> Member

@reshnashrestha 
Hi, you did it very nicely.
