### ISSUE TITLE
Add the changes in documentation

### ISSUE THREAD

**Issue by pratibha77118** [ubsuny/23-Homework4G3#74]
Hi @yasmensarhan27,
 Please add the changes you made while pylinting and pytesting the unit test in your documentation. I think professor indicated about change log (https://en.wikipedia.org/wiki/Changelog) too.

**Comment by uarif** [comment]
Did you make those changes? @pratibha77118. Can I see? Thank you.

**Comment by Mosaddeq107** [comment]
> Hi @yasmensarhan27, Please add the changes you made while pylinting and pytesting the unit test in your documentation. I think professor indicated about change log (https://en.wikipedia.org/wiki/Changelog) too.

Did you get an idea to implement the Changelog into the repository?

**Comment by Mosaddeq107** [comment]
> Did you make those changes? @pratibha77118. Can I see? Thank you.

@uarif 
Hi, what about it in your repository?

**Comment by yasmensarhan27** [comment]
Yeah
I’ll
I’m waiting till the merge request is accepted then I can add the last
pylint results

**Comment by uarif** [comment]
> > Did you make those changes? @pratibha77118. Can I see? Thank you.
> 
> @uarif Hi, what about it in your repository?

Unfortunately not. I added that to my repository, but I got some errors. I am not sure if i am doing it the correct way.

**Comment by sharmistharanit** [comment]
What exactly do we need to do? @pratibha77118 @Mosaddeq107
