### ISSUE TITLE
Which Hw?

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework4G3#8]
What's the homework you have decided to do ?

**Comment by sharmistharanit** [comment]
We have not decided it yet.

**Comment by reshnashrestha** [comment]
Oh, I saw the code from the HW3 from G5 i.e. on the projectile motion. If you are not sure, just let me know I am also thinking of working on that. @yasmensarhan27 @sharmistharanit @AhmedCode99

**Comment by sharmistharanit** [comment]
yes we will work on projectile motion with air drag.
