### ISSUE TITLE
How do I check how many issues I have created in our group? 

### ISSUE THREAD

**Issue by sharmistharanit** [ubsuny/23-Homework4G3#85]
Any help will be appreciated. @yasmensarhan27

**Comment by reshnashrestha** [comment]
Hi @sharmistharanit I am also thinking about this

**Comment by Pranjal-Srivastava-2023** [comment]
@sharmistharanit Click on the insights tab in your group repository, then click on your username, if you scroll down it shows how many issues have you created and in which repository.

**Comment by poojashresthacode** [comment]
Thanks, it helped.

**Comment by LinxuanHu** [comment]
> @sharmistharanit Click on the insights tab in your group repository, then click on your username, if you scroll down it shows how many issues have you created and in which repository.

it's really helpful

**Comment by sharmistharanit** [comment]
Thank you everyone. Yes, it works.
